Models/Art.cs
using Microsoft.AspNetCore.Mvc;

namespace ArtGallery.Models
{
    public class Art
    {
        public int Id { get; set; }
        public string Description { get; set; }

        public string origin { get; set; }

        public Boolean areyoutheartist { get; set; }

        public Boolean wantstosell { get; set; }

        public int amount { get; set; }

        //public byte[] Image { get; set; }

        //Session Management - Start
        //Session Variables
        public const string SessionKeyName = "_Name";
        public const string SessionKeyAge = "_Age";
        private readonly ILogger<Art> _logger;

        public Art(ILogger<Art> logger)
        {
            _logger = logger;
        }
        
        public void OnGet(HttpContext httpContext)
        {
            if (string.IsNullOrEmpty(httpContext.Session.GetString(SessionKeyName)))
            {
                httpContext.Session.SetString(SessionKeyName, "Parwat Lohani");
                httpContext.Session.SetInt32(SessionKeyAge, 45);
            }
            var name = httpContext.Session.GetString(SessionKeyName);

            var age = httpContext.Session.GetInt32(SessionKeyAge).ToString();

            _logger.LogInformation("Session Name: {Name}", name);
            _logger.LogInformation("Session Age: {Age}", age);
        }
        //Session Management - End

        public Art() { }
    }
}

Models/ErrorViewModel.cs
namespace ArtGallery.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ArtsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ArtGallery.Data;
using ArtGallery.Models;
using Microsoft.AspNetCore.Authorization;

namespace ArtGallery.Controllers
{
    public class ArtsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostevn;

        public ArtsController(ApplicationDbContext context, IWebHostEnvironment webHostevn)
        {
            _context = context;
            _webHostevn = webHostevn;
        }

        // GET: Arts
        public async Task<IActionResult> Index()
        {
            try 
            { 
                return View(await _context.Art.ToListAsync());  
            } 
            catch (Exception ex)
            {
                Logevents.LogToFile("Title", ex.ToString(), _webHostevn);
                return View();
            }
        }

        // GET: Arts/ShowSearchForm
        [Authorize]
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }

        // POST: Arts/ShowSearchResults
        [Authorize]
        public async Task<IActionResult> ShowSearchResults(string SearchPhrase)
        {
            return View("Index",await _context.Art.Where(j=>j.Description.Contains(SearchPhrase)).ToListAsync());
        }

        // GET: Arts/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var art = await _context.Art
                .FirstOrDefaultAsync(m => m.Id == id);
            if (art == null)
            {
                return NotFound();
            }

            return View(art);
        }

        // GET: Arts/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Arts/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Description,origin,areyoutheartist,wantstosell,amount")] Art art)
        {
            if (ModelState.IsValid)
            {
                _context.Add(art);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(art);
        }

        // GET: Arts/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var art = await _context.Art.FindAsync(id);
            if (art == null)
            {
                return NotFound();
            }
            return View(art);
        }

        // POST: Arts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Description,origin,areyoutheartist,wantstosell,amount")] Art art)
        {
            if (id != art.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(art);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArtExists(art.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(art);
        }

        // GET: Arts/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var art = await _context.Art
                .FirstOrDefaultAsync(m => m.Id == id);
            if (art == null)
            {
                return NotFound();
            }

            return View(art);
        }

        // POST: Arts/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var art = await _context.Art.FindAsync(id);
            if (art != null)
            {
                _context.Art.Remove(art);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArtExists(int id)
        {
            return _context.Art.Any(e => e.Id == id);
        }
    }
}

Controllers/HomeController.cs
using ArtGallery.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ArtGallery.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Arts/Create.cshtml
@model ArtGallery.Models.Art

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Art</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="origin" class="control-label"></label>
                <input asp-for="origin" class="form-control" />
                <span asp-validation-for="origin" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="areyoutheartist" /> @Html.DisplayNameFor(model => model.areyoutheartist)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="wantstosell" /> @Html.DisplayNameFor(model => model.wantstosell)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="amount" class="control-label"></label>
                <input asp-for="amount" class="form-control" />
                <span asp-validation-for="amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Arts/Delete.cshtml
@model ArtGallery.Models.Art

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Art</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.origin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.origin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.areyoutheartist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.areyoutheartist)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.wantstosell)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.wantstosell)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.amount)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Arts/Details.cshtml
@model ArtGallery.Models.Art

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Art</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.origin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.origin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.areyoutheartist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.areyoutheartist)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.wantstosell)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.wantstosell)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.amount)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Arts/Edit.cshtml
@model ArtGallery.Models.Art

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Art</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="origin" class="control-label"></label>
                <input asp-for="origin" class="form-control" />
                <span asp-validation-for="origin" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="areyoutheartist" /> @Html.DisplayNameFor(model => model.areyoutheartist)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="wantstosell" /> @Html.DisplayNameFor(model => model.wantstosell)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="amount" class="control-label"></label>
                <input asp-for="amount" class="form-control" />
                <span asp-validation-for="amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Arts/Index.cshtml
@model IEnumerable<ArtGallery.Models.Art>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.origin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.areyoutheartist)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.wantstosell)
            </th>           
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.origin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.areyoutheartist)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.wantstosell)
            </td>           
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Arts/ShowSearchForm.cshtml
<h4>Search for Arts</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">            
            <div class="form-group">
                <label for="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" />                
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center"><img src="background.jpg" >
    <h1 class="display-4">Welcome to your Art Gallery</h1>    
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ArtGallery</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ArtGallery.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ArtGallery</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Arts" asp-action="Index">Arts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Arts" asp-action="ShowSearchForm">Search</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ArtGallery - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>